### ISSUE TITLE
CSS Grid布局了解

### ISSUE THREAD

**Issue by gogoend** [gogoend/gogoend.github.io#20]
# 初见
## 背景
之前做一个分块展示类项目，其页面布局大致如图所示：
![image](https://user-images.githubusercontent.com/26410985/80936359-6f34d180-8e03-11ea-8ecf-af8f5611542d.png)
遇到这样的布局，在不考虑浏览器兼容性的情况下，我认为使用Grid布局应该是一种很不错的选择。在此第一次尝试了Grid布局方式；为此，我做了一个如下的简易demo。
## 简易Demo
[css/gird-layout-start.html](https://github.com/gogoend/gogoend.github.io/blob/master/css/gird-layout-start.html)
## 关于该简易Demo的简述
1. HTML结构
```html
<div class="grid-wrap">
  <section class="grid-cell" style="grid-area:cell1">1</section>
  <section class="grid-cell" style="grid-area:cell2">2</section>
  <section class="grid-cell" style="grid-area:cell3">3</section>
  <section class="grid-cell" style="grid-area:cell4">4</section>
  <section class="grid-cell" style="grid-area:cell5">5</section>
</div>
```
外层.grid-wrap是网格容器，直接在其下包含该容器下所有的网格元素。

我们需要为每一个网格元素指定一个grid-area属性，标识出该表格。这里的属性值是一个自定义字符串。

2. CSS规则定义
```css
/* 网格容器定义 */
.grid-wrap {
	height: 100%;
	display: grid;
	box-sizing: border-box;
	padding: 30px 0;
	grid-template-areas: 'cell1 cell3' 'cell1 cell4' 'cell2 cell5';
	grid-template-columns: 50% 50%;
	grid-template-rows: 25% 25% 50%;
}
/* 网格定义 */
.grid-cell {
	display: flex;
	align-items: center;
	justify-content: center;
	background-color: rgb(0,91,151);
	background-image: linear-gradient(  -30deg,  rgb(46,49,146) 0%,  rgb(30,156,215) 39.4%,  rgb(0,113,188) 72.16%,  rgb(0,91,151) 100%  );
	margin: 15px 25px;
	border-radius: 40px;
	color: #fff;
	text-align: center;
	font-size: 5em
}
```

在此只需关心网格容器（.grid-wrap）的定义。这里有几个之前没用过的属性：
1. display: grid;
将容器配置为grid容器
2. grid-template-areas: 'cell1 cell3' 'cell1 cell4' 'cell2 cell5';
配置grid布局，此处布局为三行二列布局。这样看会更好理解一些：
```
grid-template-areas: 
  'cell1 cell3'
  'cell1 cell4'
  'cell2 cell5'
;
```
3. grid-template-columns: 50% 50%;
配置grid中列宽，此处设置容器中二列的列宽。
4. grid-template-rows: 25% 25% 50%;
配置grid中行高，此处设置容器中三行的行高。
